import { Inter } from "next/font/google";
import "./globals.css";
import TransitionProvider from "@/components/TransitionProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Bertrand Menel Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-dark-background dark:text-dark-text`}>
        <div>
          <TransitionProvider>{children}</TransitionProvider>
        </div>
      </body>
    </html>
  );
}
